
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 150
#define YY_END_OF_BUFFER 151
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[360] =
    {   0,
        0,    0,  106,  106,  123,  123,    0,    0,  151,  149,
       85,   86,   84,   74,   89,  144,   75,   71,   88,   63,
       64,   62,   60,   82,   61,   70,   73,  129,  124,   80,
       81,   76,   83,   77,   79,   87,   65,  149,   66,   78,
      149,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   67,   69,   68,   72,
      106,   91,   90,  150,  123,  108,  107,  150,  148,  145,
      148,  146,   41,   49,   51,   48,   45,   38,   42,   39,
       43,   50,    0,  139,  140,   44,  139,  129,  129,    0,
        0,  131,    0,  130,    0,    0,  124,  124,    0,  126,

      125,   56,   53,   59,   54,   58,   87,   46,    0,    0,
        0,   87,   87,   87,   87,   87,   87,    8,   87,   87,
       87,   87,   87,   87,   16,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   47,   52,  106,  105,
      100,  102,   92,  103,  101,   93,   94,   95,   96,   97,
       98,   99,  105,  123,  122,  117,  119,  109,  120,  118,
      110,  111,  112,  113,  114,  115,  116,  122,    0,  147,
        0,  146,   40,    0,  129,  129,    0,    0,    0,  141,
      132,    0,  142,  134,  124,  124,  124,    0,  141,  127,
       55,   57,    0,    0,    0,   87,   87,   87,   87,   87,

       87,   87,   87,   87,   87,   87,   14,   87,   87,   18,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,  103,  104,  120,  121,
        0,    0,    0,  141,  141,  133,  142,  142,  134,  134,
      136,  135,  141,  141,  143,  128,    0,    0,    0,    1,
       87,    3,    4,   87,   87,   87,   87,   10,   11,   87,
       87,   15,   87,   19,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   32,   87,   87,  103,
      120,    0,    0,  134,  134,  134,  134,  137,   35,    0,
        0,    2,    5,   87,   87,   87,   87,   13,   87,   87,

       87,   87,   23,   87,   87,   87,   87,   87,   87,   30,
       87,   87,   34,    0,    0,    0,    0,  134,  134,  138,
        0,    0,   87,   87,    9,   12,   17,   87,   87,   22,
       24,   25,   26,   27,   28,   87,   87,   87,    0,    0,
        0,    0,   87,    7,   87,   87,   29,   87,   87,   36,
        0,    6,   20,   21,   31,   33,    0,   37,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   28,   31,   28,
       32,   32,   33,   32,   32,   34,   32,   32,   32,   35,
       32,   32,   32,   32,   36,   32,   32,   37,   32,   32,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   32,   52,   53,   54,   55,
       56,   57,   32,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    1,    2,    1,
        1,    1,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[373] =
    {   0,
        0,    0,   68,   69,   70,   71,   77,   81,  579,  580,
      580,  580,  580,  553,  580,  580,  552,   66,  580,  580,
      580,  551,   67,  580,   69,   69,  550,   94,  142,  580,
      580,   80,  549,   91,  580,    0,  580,   56,  580,  548,
       89,  511,  513,   56,   76,   71,   81,  514,   88,  513,
      521,   89,  502,  511,  509,  514,  580,   96,  580,  580,
        0,  580,  580,  194,    0,  580,  580,  253,  580,  580,
      121,  125,  580,  580,  580,  580,  580,  580,  580,  580,
      580,  580,  546,  134,  580,  580,  146,  105,  151,  177,
      170,  528,  189,  580,    0,  110,  198,    0,  206,  527,

      580,  535,  580,  580,  580,  534,    0,  580,  502,  501,
      502,  495,  507,  494,  509,  496,  502,  488,  489,  486,
      486,  489,  486,  483,    0,   97,  487,  133,  485,  136,
      163,  489,  482,   97,  172,  487,  580,  580,    0,  580,
      580,  580,  209,  211,  580,  580,  580,  580,  580,  580,
      580,  580,    0,    0,  580,  580,  580,  220,  224,  580,
      580,  580,  580,  580,  580,  580,  580,    0,  226,  580,
      534,  226,  580,    0,  204,    0,  259,  301,  230,  250,
      500,  240,  262,  268,    0,  211,  246,  264,  307,  499,
      580,  580,  478,  479,  489,  475,  487,  482,  470,  240,

      484,  482,  478,  470,  476,  479,    0,  465,  469,    0,
      470,  467,  457,  455,  457,  459,  466,  452,  450,  450,
      462,  452,  456,  460,  462,  451,  290,    0,  304,    0,
      310,    0,  322,  314,  331,  580,  343,  351,  340,  354,
      469,  580,  361,  364,  580,  580,  449,  444,  451,    0,
      447,    0,    0,  438,  446,  435,  442,    0,    0,  436,
      433,    0,  437,    0,  432,  432,  431,  428,  440,  430,
      434,  439,  438,  421,  411,  407,    0,  394,  384,  580,
      580,  368,  370,    0,  373,  376,  379,  394,  580,  376,
      377,    0,    0,  356,  357,  339,  323,    0,  329,  308,

      315,  301,    0,  308,  299,  301,  284,  287,  272,    0,
      259,  261,    0,    0,  382,  387,  394,  397,  400,  580,
      258,  240,  232,  231,    0,    0,    0,  239,  232,    0,
        0,    0,    0,    0,    0,  226,  217,  204,  403,  406,
      191,  210,  189,    0,  153,  147,    0,  155,  148,  580,
      129,    0,    0,    0,    0,    0,  118,  580,  580,  432,
      438,  444,  446,  452,  458,  464,  470,  476,  174,  170,
      133,   77
    } ;

static yyconst flex_int16_t yy_def[373] =
    {   0,
      359,    1,  360,  360,  361,  361,  362,  362,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  363,  359,  359,  359,  359,
      359,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  359,  359,  359,  359,
      364,  359,  359,  365,  366,  359,  359,  367,  359,  359,
      368,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,   28,   28,  359,
      359,  359,  359,  359,  369,  359,   29,   29,  359,  359,

      359,  359,  359,  359,  359,  359,  363,  359,  359,  359,
      359,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  359,  359,  364,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  370,  366,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  371,  368,  359,
      368,  359,  359,  372,   89,   89,  359,  359,  359,  359,
      359,  359,  359,  369,   97,   97,   29,  359,  359,  359,
      359,  359,  359,  359,  359,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  359,  370,  359,  371,
      372,  178,  359,  359,  359,  359,  359,  359,  184,  184,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  359,
      359,  231,  231,  239,  184,  239,  184,  359,  359,  359,
      359,  363,  363,  363,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  282,  231,  282,  231,  239,  184,  359,
      359,  359,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  282,  231,
      359,  359,  363,  363,  363,  363,  363,  363,  363,  359,
      359,  363,  363,  363,  363,  363,  359,  359,    0,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359
    } ;

static yyconst flex_int16_t yy_nxt[651] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       29,   30,   31,   32,   33,   34,   35,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   36,
       49,   36,   50,   36,   36,   36,   36,   51,   52,   53,
       54,   55,   56,   36,   36,   36,   57,   58,   59,   60,
       62,   62,   66,   66,   75,   67,   67,   63,   63,   70,
       78,  231,   71,   70,   80,   83,   71,   84,   84,   84,
       76,   79,   95,   81,   82,   72,   72,   72,  114,   72,

       72,   72,   85,  102,  103,  115,   64,   64,   68,   68,
       87,  116,   88,   89,   90,  105,  106,  109,  110,   95,
      137,  111,  117,  119,   91,  120,  170,   92,   93,   94,
       95,  118,   96,  122,  121,  125,  123,  230,  129,  130,
       91,  174,  126,  172,  172,  172,  174,  222,  131,  209,
       93,  132,   84,   84,   84,  223,  210,   95,   87,  171,
       97,   98,   98,  138,   84,   84,   84,   85,  174,  175,
      176,  177,   99,  174,  228,  100,   93,  101,  184,   85,
       96,  212,  358,  179,  216,  179,  357,  359,   99,  180,
      180,  213,  214,   87,  356,  178,  177,  177,   93,  141,

      355,  217,  182,  142,  182,  218,  354,   91,  183,  183,
      353,   93,  143,  144,  359,   96,  185,  186,  187,  188,
      219,  188,  224,   91,  225,  189,  189,  227,  227,  227,
      227,  170,  145,   93,  174,  352,  146,  147,  229,  229,
      174,  148,  229,  229,  172,  172,  172,  359,  149,  180,
      180,  150,  351,  151,  350,  152,  349,  153,  156,  183,
      183,  174,  157,  348,  171,  187,  187,  174,  234,  235,
      235,  158,  159,  347,  359,   87,  346,  178,  177,  177,
      237,  238,  238,  189,  189,  345,  239,  240,  240,   91,
      344,  160,  343,   93,  342,  161,  162,   96,  254,  255,

      163,  241,   93,  242,  341,   91,   96,  164,  280,  280,
      165,  338,  166,  337,  167,   93,  168,   87,  336,  232,
      233,  177,  281,  281,   93,  243,  244,  244,  282,  283,
      283,   91,  234,  235,  235,   93,  335,  174,   87,   96,
      232,  233,  177,  334,   93,  333,  332,   91,   96,  234,
      235,  235,   91,  331,  245,  330,   93,   93,  284,  285,
       96,  237,  238,  238,  174,  329,   93,  328,   91,  237,
      238,  238,  286,  287,  287,  327,  174,  326,   93,  243,
      244,  244,  243,  244,  244,  325,  314,  315,  316,  317,
      317,  318,  319,  287,  318,  319,  287,  286,  287,  287,

      339,  340,  317,  174,  174,  339,  340,  317,  245,  324,
      323,  245,  316,  317,  317,  318,  319,  287,  318,  319,
      287,  339,  340,  317,  339,  340,  317,  322,  321,  320,
      313,  174,   61,   61,   61,   61,   61,   61,   65,   65,
       65,   65,   65,   65,   69,   69,   69,   69,   69,   69,
      107,  107,  139,  312,  139,  311,  139,  139,  140,  140,
      140,  140,  140,  140,  154,  310,  309,  154,  154,  154,
      155,  155,  155,  155,  155,  155,  169,  169,  169,  169,
      169,  169,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,

      290,  289,  288,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  253,  252,  251,
      250,  249,  248,  247,  246,  236,  359,  226,  221,  220,
      215,  211,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  181,  173,  136,  135,  134,  133,  128,  127,  124,
      113,  112,  108,  104,   86,   77,   74,   73,  359,    9,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359
    } ;

static yyconst flex_int16_t yy_chk[651] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    6,   18,    5,    6,    3,    4,    7,
       23,  372,    7,    8,   25,   26,    8,   26,   26,   26,
       18,   23,   38,   25,   25,    7,    7,    7,   44,    8,

        8,    8,   26,   32,   32,   44,    3,    4,    5,    6,
       28,   44,   28,   28,   28,   34,   34,   41,   41,   38,
       58,   41,   45,   46,   28,   46,   71,   28,   28,   28,
       28,   45,   28,   47,   46,   49,   47,  371,   52,   52,
       28,   88,   49,   72,   72,   72,   96,  134,   52,  126,
       28,   52,   84,   84,   84,  134,  126,   28,   29,   71,
       29,   29,   29,   58,   87,   87,   87,   84,   88,   89,
       89,   89,   29,   96,  370,   29,   29,   29,  369,   87,
       29,  128,  357,   91,  130,   91,  351,   89,   29,   91,
       91,  128,  128,   90,  349,   90,   90,   90,   29,   64,

      348,  130,   93,   64,   93,  131,  346,   90,   93,   93,
      345,   90,   64,   64,   89,   90,   97,   97,   97,   99,
      131,   99,  135,   90,  135,   99,   99,  143,  143,  144,
      144,  169,   64,   90,   97,  343,   64,   64,  158,  158,
      175,   64,  159,  159,  172,  172,  172,  186,   64,  179,
      179,   64,  342,   64,  341,   64,  338,   64,   68,  182,
      182,   97,   68,  337,  169,  187,  187,  175,  180,  180,
      180,   68,   68,  336,  186,  177,  329,  177,  177,  177,
      183,  183,  183,  188,  188,  328,  184,  184,  184,  177,
      324,   68,  323,  177,  322,   68,   68,  177,  200,  200,

       68,  184,  184,  184,  321,  177,  184,   68,  227,  227,
       68,  312,   68,  311,   68,  177,   68,  178,  309,  178,
      178,  178,  229,  229,  184,  189,  189,  189,  231,  231,
      231,  178,  234,  234,  234,  178,  308,  178,  233,  178,
      233,  233,  233,  307,  231,  306,  305,  178,  231,  235,
      235,  235,  233,  304,  189,  302,  233,  178,  239,  239,
      233,  237,  237,  237,  178,  301,  231,  300,  233,  238,
      238,  238,  240,  240,  240,  299,  239,  297,  233,  243,
      243,  243,  244,  244,  244,  296,  282,  282,  283,  283,
      283,  285,  285,  285,  286,  286,  286,  287,  287,  287,

      315,  315,  315,  239,  282,  316,  316,  316,  243,  295,
      294,  244,  317,  317,  317,  318,  318,  318,  319,  319,
      319,  339,  339,  339,  340,  340,  340,  291,  290,  288,
      279,  282,  360,  360,  360,  360,  360,  360,  361,  361,
      361,  361,  361,  361,  362,  362,  362,  362,  362,  362,
      363,  363,  364,  278,  364,  276,  364,  364,  365,  365,
      365,  365,  365,  365,  366,  275,  274,  366,  366,  366,
      367,  367,  367,  367,  367,  367,  368,  368,  368,  368,
      368,  368,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  263,  261,  260,  257,  256,  255,  254,  251,  249,

      248,  247,  241,  226,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  215,  214,  213,  212,  211,  209,
      208,  206,  205,  204,  203,  202,  201,  199,  198,  197,
      196,  195,  194,  193,  190,  181,  171,  136,  133,  132,
      129,  127,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  106,  102,
      100,   92,   83,   56,   55,   54,   53,   51,   50,   48,
       43,   42,   40,   33,   27,   22,   17,   14,    9,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "eslex.l"
#line 3 "eslex.l"
//EUGENE SOKOLOV
//COMPILERS ECE466
//LEXICAL ANALYSIS: lex.l

//#include "tokens-manual.h"
//#include "yylval.h"
#include "esparser.tab.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include "sym_table.h"

YYSTYPE yylval;

unsigned int lineno = 1;
unsigned int string_length = 0;
char filename[MAX_STRING_LENGTH];
char *tmp_ptr;
char tmp_string[MAX_STRING_LENGTH];

void keyword(int lineno, char* yytext);
void printchars(char *str, char *end);


#line 750 "lex.yy.c"

#define INITIAL 0
#define IN_CHAR 1
#define IN_STRING 2
#define IN_FILE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 36 "eslex.l"


#line 943 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 360 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 580 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 38 "eslex.l"
{keyword(lineno,yytext);return AUTO;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "eslex.l"
{keyword(lineno,yytext);return BREAK;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "eslex.l"
{keyword(lineno,yytext);return CASE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "eslex.l"
{keyword(lineno,yytext);return CHAR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "eslex.l"
{keyword(lineno,yytext);return CONST;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "eslex.l"
{keyword(lineno,yytext);return CONTINUE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "eslex.l"
{keyword(lineno,yytext);return DEFAULT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 45 "eslex.l"
{keyword(lineno,yytext);return DO;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 46 "eslex.l"
{keyword(lineno,yytext);return DOUBLE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "eslex.l"
{keyword(lineno,yytext);return ELSE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "eslex.l"
{keyword(lineno,yytext);return ENUM;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "eslex.l"
{keyword(lineno,yytext);return EXTERN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "eslex.l"
{keyword(lineno,yytext);return FLOAT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 51 "eslex.l"
{keyword(lineno,yytext);return FOR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "eslex.l"
{keyword(lineno,yytext);return GOTO;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 53 "eslex.l"
{keyword(lineno,yytext);return IF;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 54 "eslex.l"
{keyword(lineno,yytext);return INLINE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 55 "eslex.l"
{keyword(lineno,yytext);return INT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 56 "eslex.l"
{keyword(lineno,yytext);return LONG;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 57 "eslex.l"
{keyword(lineno,yytext);return REGISTER;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 58 "eslex.l"
{keyword(lineno,yytext);return RESTRICT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 59 "eslex.l"
{keyword(lineno,yytext);return RETURN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 60 "eslex.l"
{keyword(lineno,yytext);return SHORT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 61 "eslex.l"
{keyword(lineno,yytext);return SIGNED;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "eslex.l"
{keyword(lineno,yytext);return SIZEOF;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 63 "eslex.l"
{keyword(lineno,yytext);return STATIC;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 64 "eslex.l"
{keyword(lineno,yytext);return STRUCT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 65 "eslex.l"
{keyword(lineno,yytext);return SWITCH;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 66 "eslex.l"
{keyword(lineno,yytext);return TYPEDEF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "eslex.l"
{keyword(lineno,yytext);return UNION;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "eslex.l"
{keyword(lineno,yytext);return UNSIGNED;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 69 "eslex.l"
{keyword(lineno,yytext);return VOID;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 70 "eslex.l"
{keyword(lineno,yytext);return VOLATILE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 71 "eslex.l"
{keyword(lineno,yytext);return WHILE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "eslex.l"
{keyword(lineno,yytext);return _BOOL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 73 "eslex.l"
{keyword(lineno,yytext);return _COMPLEX;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 74 "eslex.l"
{keyword(lineno,yytext);return _IMAGINARY;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "eslex.l"
{return PLUSPLUS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "eslex.l"
{return MINUSMINUS;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "eslex.l"
{return ELLIPSIS;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 79 "eslex.l"
{return NOTEQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 80 "eslex.l"
{return PLUSEQ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 81 "eslex.l"
{return MINUSEQ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "eslex.l"
{return DIVEQ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "eslex.l"
{return TIMESEQ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "eslex.l"
{return XOREQ;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "eslex.l"
{return OREQ;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "eslex.l"
{return ANDEQ;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "eslex.l"
{return MODEQ;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "eslex.l"
{return INDSEL;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "eslex.l"
{return LOGAND;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "eslex.l"
{return LOGOR;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "eslex.l"
{return LTEQ;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "eslex.l"
{return GTEQ;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "eslex.l"
{return SHLEQ;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "eslex.l"
{return SHL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "eslex.l"
{return SHREQ;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "eslex.l"
{return SHR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 97 "eslex.l"
{return EQEQ;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 98 "eslex.l"
{return '+';}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 99 "eslex.l"
{return '-';}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 100 "eslex.l"
{return '*';}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "eslex.l"
{return '(';}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "eslex.l"
{return ')';}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 103 "eslex.l"
{return '[';}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 104 "eslex.l"
{return ']';}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 105 "eslex.l"
{return '{';}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 106 "eslex.l"
{return '}';}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 107 "eslex.l"
{return '|';}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 108 "eslex.l"
{return '.';}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 109 "eslex.l"
{return '&';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 110 "eslex.l"
{return '~';}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 111 "eslex.l"
{return '/';}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 112 "eslex.l"
{return '!';}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 113 "eslex.l"
{return '%';}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 114 "eslex.l"
{return '<';}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 115 "eslex.l"
{return '>';}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 116 "eslex.l"
{return '^';}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 117 "eslex.l"
{return '?';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 118 "eslex.l"
{return ':';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 119 "eslex.l"
{return ';';}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 120 "eslex.l"
{return ',';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 121 "eslex.l"
{return '=';}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 123 "eslex.l"
{}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 124 "eslex.l"
{}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 125 "eslex.l"
{lineno++;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 127 "eslex.l"
{
	yylval.yystring=strdup(yytext);
	//yylval.yystring_size=strlen(yytext);
	return IDENT;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 133 "eslex.l"
{tmp_ptr=tmp_string;string_length=0;BEGIN(IN_CHAR);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 134 "eslex.l"
{tmp_ptr=tmp_string;string_length=0;BEGIN(IN_STRING);}
	YY_BREAK

case 90:
YY_RULE_SETUP
#line 137 "eslex.l"
{
	BEGIN(INITIAL); 
	*tmp_ptr = '\0'; 
	yylval.yychar = tmp_string[0]; 
	return CHARLIT;
	}
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 143 "eslex.l"
{fprintf(stderr, "%s:%d:Error:Unterminated string constant\n", filename, lineno);exit(1);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 144 "eslex.l"
{*tmp_ptr='\0';tmp_ptr++;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 145 "eslex.l"
{*tmp_ptr='\a';tmp_ptr++;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 146 "eslex.l"
{*tmp_ptr='\b';tmp_ptr++;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 147 "eslex.l"
{*tmp_ptr='\f';tmp_ptr++;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 148 "eslex.l"
{*tmp_ptr='\n';tmp_ptr++;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 149 "eslex.l"
{*tmp_ptr='\r';tmp_ptr++;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 150 "eslex.l"
{*tmp_ptr='\t';tmp_ptr++;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 151 "eslex.l"
{*tmp_ptr='\v';tmp_ptr++;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 152 "eslex.l"
{*tmp_ptr='\"';tmp_ptr++;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 153 "eslex.l"
{*tmp_ptr='\\';tmp_ptr++;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 154 "eslex.l"
{*tmp_ptr='\'';tmp_ptr++;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 155 "eslex.l"
{
        int tmp;
        sscanf(yytext+1, "%o", &tmp);
        if (tmp > 0xff){
            fprintf(stderr, "%s:%d:Warning:Octal escape sequence %s out of range", filename, lineno, yytext);
            tmp = '\377';
        }
        *tmp_ptr=tmp;
	tmp_ptr++;
    }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 165 "eslex.l"
{
        int tmp;
        sscanf(yytext+2, "%x", &tmp);
        if (tmp > 0xff){
            fprintf(stderr, "%s:%d:Warning:Hex escape sequence %s out of range", filename, lineno, yytext);
            tmp = '\377';
        }
        *tmp_ptr=tmp;
	tmp_ptr++;
    }
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 175 "eslex.l"
{*tmp_ptr=yytext[1];tmp_ptr++;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 176 "eslex.l"
{
	char *yptr = yytext;
        while (*yptr){
		*tmp_ptr = *yptr++;
		tmp_ptr++;
	}
    }
	YY_BREAK


case 107:
YY_RULE_SETUP
#line 186 "eslex.l"
{
	BEGIN(INITIAL); 
	*tmp_ptr = '\0'; 
	yylval.yystring = strdup(tmp_string); 
	return STRING;
	}
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 192 "eslex.l"
{fprintf(stderr, "%s:%d:Error:Unterminated string constant\n", filename, lineno);exit(1);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 193 "eslex.l"
{*tmp_ptr='\0';tmp_ptr++;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 194 "eslex.l"
{*tmp_ptr='\a';tmp_ptr++;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 195 "eslex.l"
{*tmp_ptr='\b';tmp_ptr++;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 196 "eslex.l"
{*tmp_ptr='\f';tmp_ptr++;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 197 "eslex.l"
{*tmp_ptr='\n';tmp_ptr++;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 198 "eslex.l"
{*tmp_ptr='\r';tmp_ptr++;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 199 "eslex.l"
{*tmp_ptr='\t';tmp_ptr++;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 200 "eslex.l"
{*tmp_ptr='\v';tmp_ptr++;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 201 "eslex.l"
{*tmp_ptr='\"';tmp_ptr++;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 202 "eslex.l"
{*tmp_ptr='\\';tmp_ptr++;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 203 "eslex.l"
{*tmp_ptr='\'';tmp_ptr++;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 204 "eslex.l"
{
        int tmp;
        sscanf(yytext+1, "%o", &tmp);
        if (tmp > 0xff){
            fprintf(stderr, "%s:%d:Warning:Octal escape sequence %s out of range\n", filename, lineno, yytext);
            tmp = '\377';
        }
        *tmp_ptr=tmp;
	tmp_ptr++;
    }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 214 "eslex.l"
{
        int tmp;
        sscanf(yytext+2, "%x", &tmp);
        if (tmp > 0xff){
            fprintf(stderr, "%s:%d:Warning:Hex escape sequence %s out of range\n", filename, lineno, yytext);
            tmp = '\377';
        }
        *tmp_ptr=tmp;
	tmp_ptr++;
    }
	YY_BREAK
case 122:
/* rule 122 can match eol */
YY_RULE_SETUP
#line 224 "eslex.l"
{*tmp_ptr=yytext[1];tmp_ptr++;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 225 "eslex.l"
{
        char *yptr = yytext;
        while (*yptr){
		*tmp_ptr=*yptr++;
		*tmp_ptr++;
	}
    }
	YY_BREAK

case 124:
YY_RULE_SETUP
#line 234 "eslex.l"
{
	yylval.number.yyint=atoi(yytext);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 240 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	yylval.number.yyint=atoi(yytext);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 248 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	yylval.number.yyint=atoi(yytext);
	yylval.number.num_type=TYPE_LONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 255 "eslex.l"
{	
	yytext[yyleng-2] = '\0';
	yylval.number.yyint=atoi(yytext);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 262 "eslex.l"
{
	yytext[yyleng-3] = '\0';
	yylval.number.yyint=atoi(yytext);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 270 "eslex.l"
{
	sscanf(yytext, "%llo", &yylval.number.yyint);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 276 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%llo", &yylval.number.yyint);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 283 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%llo", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 290 "eslex.l"
{
	yytext[yyleng-2] = '\0';
	sscanf(yytext, "%llo", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 297 "eslex.l"
{
	yytext[yyleng-3] = '\0';
	sscanf(yytext, "%llo", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 305 "eslex.l"
{
	sscanf(yytext, "%llx", &yylval.number.yyint);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 311 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%llx", &yylval.number.yyint);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 318 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%llx", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 325 "eslex.l"
{
	yytext[yyleng-2] = '\0';
	sscanf(yytext, "%llx", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 332 "eslex.l"
{
	yytext[yyleng-3] = '\0';
	sscanf(yytext, "%llx", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 340 "eslex.l"
{
	sscanf(yytext, "%Lf", &yylval.number.yydouble);
	yylval.number.num_type=TYPE_DOUBLE;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 346 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%Lf", &yylval.number.yydouble);
	yylval.number.num_type=TYPE_LONGDOUBLE;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 354 "eslex.l"
{
	sscanf(yytext, "%Lf", &yylval.number.yydouble);
	yylval.number.num_type=TYPE_DOUBLE;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 360 "eslex.l"
{
	sscanf(yytext, "%Lf", &yylval.number.yydouble);
	yylval.number.num_type=TYPE_DOUBLE;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 367 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%Lf", &yylval.number.yydouble);
	yylval.number.num_type=TYPE_FLOAT;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 375 "eslex.l"
{BEGIN(IN_FILE);}
	YY_BREAK

case 145:
/* rule 145 can match eol */
YY_RULE_SETUP
#line 377 "eslex.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 378 "eslex.l"
{}
	YY_BREAK
case 147:
/* rule 147 can match eol */
YY_RULE_SETUP
#line 379 "eslex.l"
{strncpy(filename, yytext+1, strlen(yytext)-2);filename[strlen(yytext)-2]='\0';}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 380 "eslex.l"
{}
	YY_BREAK

case 149:
YY_RULE_SETUP
#line 383 "eslex.l"
{fprintf(stderr,"Lexical error: undefined token: %s\n", yytext);exit(1);}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 385 "eslex.l"
ECHO;
	YY_BREAK
#line 1965 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_CHAR):
case YY_STATE_EOF(IN_STRING):
case YY_STATE_EOF(IN_FILE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 360 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 360 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 359);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 385 "eslex.l"



void printchars(char *str, char *end){
/*
	while (str != end){
		switch (*str){
		    case '\0':
		        printf("\\0");
		    case '\a':
		        printf("\\a");
		        break;
		    case '\b':
		        printf("\\b");
		        break;
		    case '\f':
		        printf("\\f");
		        break;
		    case '\n':
		        printf("\\n");
		        break;
		    case '\r':
		        printf("\\r");
		        break;
		    case '\t':
		        printf("\\t");
		        break;
		    case '\v':
		        printf("\\v");
		        break;
		    case '\"':
		        printf("\\\"");
		        break;
		        break;
		    case '\\':
		        printf("\\\\");
		        break;
		    case '\'':
		        printf("\\\'");
		        break;
		    default:
		        if (*str > 126 || *str < 32){
		            printf("\\%03o", (unsigned char)*str);
		        } else {
		            printf("%c", *str);
		        }
		        break;
		}
		str++;
    	}
	printf("\n");
*/
}

void keyword(int lineno, char* yytext){
/*
	char *p = yytext;
	while(*p != '\0'){
		*p=toupper(*p);
 		p++;
	}
 	printf("%s\t %d\t %s\n",filename, lineno, yytext);
*/
}

/*
int main(){
   int token;
   while(token=yylex()){
	switch(token){
		case IDENT:
			printf("%s\t %d\t IDENT\t %s\n",filename, lineno, yylval.yystring);
			break;
		case STRING:
			printf("%s\t %d\t STRING\t ",filename, lineno);
			printchars(tmp_string, tmp_ptr);	
			break;
		case CHARLIT:
			printf("%s\t %d\t CHARLIT\t ",filename, lineno);
			printchars(tmp_string, tmp_string+1);	
			break;
		case NUMBER:
			printf("%s\t %d\t NUMBER\t",filename,lineno);
			if(yylval.number.num_type==TYPE_INT || yylval.number.num_type==TYPE_LONG)
				printf("INTEGER\t %lld\t", yylval.number.yyint);
			else
				printf("REAL\t %Lg\t", yylval.number.yydouble);
			if(yylval.number.num_sign==TYPE_UNSIGNED)
				printf("UNSIGNED,");
			switch(yylval.number.num_type){
				case TYPE_INT:	printf("INT\n");break;
				case TYPE_LONG:	printf("LONG\n");break;
				case TYPE_LONGLONG: printf("LONGLONG\n");break;
				case TYPE_LONGDOUBLE: printf("LONGDOUBLE\n");break;
				case TYPE_DOUBLE: printf("DOUBLE\n");break;
				case TYPE_FLOAT: printf("FLOAT\n");break;
				default: printf("error\n");break;
			}
			break;
		default:
			break;

	}

   }
}
*/

