
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 125
#define YY_END_OF_BUFFER 126
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[348] =
    {   0,
        0,    0,   81,   81,   98,   98,    0,    0,  126,  124,
       61,   60,   64,  119,   60,   60,   63,   60,   60,   60,
       60,   60,   60,  104,   99,   60,   60,   60,   62,  124,
       60,  124,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   60,   81,   66,
       65,  125,   98,   83,   82,  125,  123,  120,  123,  121,
       41,   49,   51,   48,   45,   38,   42,   39,   43,   50,
        0,  114,  115,   44,  114,  104,  104,    0,    0,  106,
        0,  105,    0,    0,   99,   99,    0,  101,  100,   56,
       53,   59,   54,   58,   62,   46,    0,    0,    0,   62,

       62,   62,   62,   62,   62,    8,   62,   62,   62,   62,
       62,   62,   16,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   47,   52,   81,   80,   75,   77,
       67,   78,   76,   68,   69,   70,   71,   72,   73,   74,
       80,   98,   97,   92,   94,   84,   95,   93,   85,   86,
       87,   88,   89,   90,   91,   97,    0,  122,    0,  121,
       40,    0,  104,  104,    0,    0,    0,  116,  107,    0,
      117,  109,   99,   99,   99,    0,  116,  102,   55,   57,
        0,    0,    0,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   14,   62,   62,   18,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   78,   79,   95,   96,    0,    0,
        0,  116,  116,  108,  117,  117,  109,  109,  111,  110,
      116,  116,  118,  103,    0,    0,    0,    1,   62,    3,
        4,   62,   62,   62,   62,   10,   11,   62,   62,   15,
       62,   19,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   32,   62,   62,   78,   95,    0,
        0,  109,  109,  109,  109,  112,   35,    0,    0,    2,
        5,   62,   62,   62,   62,   13,   62,   62,   62,   62,
       23,   62,   62,   62,   62,   62,   62,   30,   62,   62,

       34,    0,    0,    0,    0,  109,  109,  113,    0,    0,
       62,   62,    9,   12,   17,   62,   62,   22,   24,   25,
       26,   27,   28,   62,   62,   62,    0,    0,    0,    0,
       62,    7,   62,   62,   29,   62,   62,   36,    0,    6,
       20,   21,   31,   33,    0,   37,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   26,   29,   26,
       30,   30,   31,   30,   30,   32,   30,   30,   30,   33,
       30,   30,   30,   30,   34,   30,   30,   35,   30,   30,
       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   30,   50,   51,   52,   53,
       54,   55,   30,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    5,    6,
        6,    6,    6,    6,    6,    1,    2,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[361] =
    {   0,
        0,    0,   67,   68,   69,   70,   75,   78,  577,  578,
      578,  553,  578,  578,  552,   76,  578,  578,  551,   66,
       67,   69,  550,   93,  141,   80,  549,   90,    0,   74,
      548,   88,  511,  513,   83,   75,   70,   88,  514,   87,
      513,  521,   86,  502,  511,  509,  514,   75,    0,  578,
      578,  193,    0,  578,  578,  252,  578,  578,   81,  132,
      578,  578,  578,  578,  578,  578,  578,  578,  578,  578,
      546,  135,  578,  578,  144,  110,  147,  162,  171,  528,
      186,  578,    0,  122,  196,    0,  204,  527,  578,  535,
      578,  578,  578,  534,    0,  578,  502,  501,  502,  495,

      507,  494,  509,  496,  502,  488,  489,  486,  486,  489,
      486,  483,    0,  136,  487,  145,  485,   53,  152,  489,
      482,  163,  120,  487,  578,  578,    0,  578,  578,  578,
      207,  209,  578,  578,  578,  578,  578,  578,  578,  578,
        0,    0,  578,  578,  578,  211,  215,  578,  578,  578,
      578,  578,  578,  578,  578,    0,  184,  578,  533,  219,
      578,    0,  205,    0,  246,  300,  223,  226,  500,  229,
      254,  306,    0,  215,  262,  266,  285,  499,  578,  578,
      478,  479,  489,  475,  487,  482,  470,  229,  484,  482,
      478,  470,  476,  479,    0,  465,  469,    0,  470,  467,

      457,  455,  457,  459,  466,  452,  450,  450,  462,  452,
      456,  460,  462,  451,  278,    0,  282,    0,  309,    0,
      334,  303,  339,  578,  351,  355,  330,  358,  469,  578,
      363,  366,  578,  578,  449,  444,  451,    0,  447,    0,
        0,  438,  446,  435,  442,    0,    0,  436,  433,    0,
      437,    0,  432,  432,  431,  428,  440,  415,  419,  415,
      413,  367,  357,  361,    0,  345,  357,  578,  578,  369,
      376,    0,  379,  382,  388,  357,  578,  339,  339,    0,
        0,  325,  315,  315,  306,    0,  309,  292,  295,  288,
        0,  292,  288,  289,  272,  268,  268,    0,  258,  260,

        0,    0,  396,  399,  402,  405,  408,  578,  262,  253,
      238,  234,    0,    0,    0,  245,  245,    0,    0,    0,
        0,    0,    0,  236,  233,  225,  411,  415,  212,  227,
      221,    0,  206,  201,    0,  213,  209,  578,  196,    0,
        0,    0,    0,    0,  156,  578,  578,  434,  440,  446,
      448,  454,  460,  466,  472,  478,  201,  163,  141,  138
    } ;

static yyconst flex_int16_t yy_def[361] =
    {   0,
      347,    1,  348,  348,  349,  349,  350,  350,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  351,  347,
      347,  347,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  347,  352,  347,
      347,  353,  354,  347,  347,  355,  347,  347,  356,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,   24,   24,  347,  347,  347,
      347,  347,  357,  347,   25,   25,  347,  347,  347,  347,
      347,  347,  347,  347,  351,  347,  347,  347,  347,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  347,  347,  352,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      358,  354,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  359,  356,  347,  356,  347,
      347,  360,   77,   77,  347,  347,  347,  347,  347,  347,
      347,  357,   85,   85,   25,  347,  347,  347,  347,  347,
      347,  347,  347,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  347,  358,  347,  359,  360,  166,
      347,  347,  347,  347,  347,  347,  172,  172,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  347,  347,  219,
      219,  227,  172,  227,  172,  347,  347,  347,  347,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  270,  219,  270,  219,  227,  172,  347,  347,  347,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  270,  219,  347,  347,
      351,  351,  351,  351,  351,  351,  351,  347,  347,  351,
      351,  351,  351,  351,  347,  347,    0,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347
    } ;

static yyconst flex_int16_t yy_nxt[647] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       19,   20,   18,   21,   22,   23,   24,   25,   25,   18,
       18,   26,   27,   28,   18,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   18,   30,   18,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   29,   40,   29,
       41,   29,   29,   29,   29,   42,   43,   44,   45,   46,
       47,   29,   29,   29,   18,   48,   18,   18,   50,   50,
       54,   54,   55,   55,   51,   51,   58,   66,   59,   58,
       68,   59,   63,   71,  158,   72,   72,   72,   67,   69,
       70,   60,   60,   60,   60,   60,   60,  125,   64,  204,

       73,   90,   91,   52,   52,   56,   56,   75,   83,   76,
       77,   78,   93,   94,   97,   98,  205,  159,   99,  105,
      107,   79,  108,  102,   80,   81,   82,   83,  106,   84,
      103,  109,  113,  117,  118,   83,  104,   79,  110,  114,
      126,  111,  219,  119,  162,  218,  120,   81,  160,  160,
      160,   72,   72,   72,   83,   75,  162,   85,   86,   86,
       72,   72,   72,  163,  164,  165,   73,  216,  212,   87,
      213,  162,   88,   81,   89,   73,   75,   84,  166,  165,
      165,  347,  167,  162,  167,   87,  197,  158,  168,  168,
       79,  200,  206,  198,   81,   81,  129,  170,   84,  170,

      130,  201,  202,  171,  171,  172,   79,  207,  347,  131,
      132,  210,  173,  174,  175,  176,   81,  176,  346,  211,
      159,  177,  177,  215,  215,  215,  215,  217,  217,  133,
      162,  217,  217,  134,  135,  160,  160,  160,  136,  162,
      168,  168,  222,  223,  223,  137,  171,  171,  138,  347,
      139,  345,  140,  344,  141,  144,  343,  162,  342,  145,
       75,  341,  166,  165,  165,  340,  162,  339,  146,  147,
      225,  226,  226,  338,   79,  337,  347,  336,   81,  175,
      175,  335,   84,  177,  177,  242,  243,  334,  148,  333,
       79,  332,  149,  150,  268,  268,  331,  151,  269,  269,

       81,  231,  232,  232,  152,  330,  329,  153,  326,  154,
      325,  155,  324,  156,   75,  323,  220,  221,  165,  222,
      223,  223,  227,  228,  228,  270,  271,  271,   79,  322,
      233,  321,   81,  320,  162,  319,   84,  229,   81,  230,
      318,   81,   84,  317,   79,   84,  272,  273,   75,  316,
      220,  221,  165,  315,   81,  222,  223,  223,  314,  313,
       81,  162,   79,   81,  162,  312,   81,  225,  226,  226,
       84,  225,  226,  226,  274,  275,  275,  311,   79,  231,
      232,  232,  231,  232,  232,  302,  303,  310,   81,  309,
      308,  162,  304,  305,  305,  306,  307,  275,  306,  307,

      275,  301,  300,  162,  274,  275,  275,  299,  233,  298,
      297,  233,  327,  328,  305,  327,  328,  305,  304,  305,
      305,  306,  307,  275,  306,  307,  275,  327,  328,  305,
      162,  327,  328,  305,   49,   49,   49,   49,   49,   49,
       53,   53,   53,   53,   53,   53,   57,   57,   57,   57,
       57,   57,   95,   95,  127,  296,  127,  295,  127,  127,
      128,  128,  128,  128,  128,  128,  142,  294,  293,  142,
      142,  142,  143,  143,  143,  143,  143,  143,  157,  157,
      157,  157,  157,  157,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,

      276,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  241,  240,  239,  238,  237,
      236,  235,  234,  224,  347,  214,  209,  208,  203,  199,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  169,
      161,  124,  123,  122,  121,  116,  115,  112,  101,  100,
       96,   92,   74,   65,   62,   61,  347,    9,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347
    } ;

static yyconst flex_int16_t yy_chk[647] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    6,    5,    6,    3,    4,    7,   20,    7,    8,
       21,    8,   16,   22,   59,   22,   22,   22,   20,   21,
       21,    7,    7,    7,    8,    8,    8,   48,   16,  118,

       22,   26,   26,    3,    4,    5,    6,   24,   30,   24,
       24,   24,   28,   28,   32,   32,  118,   59,   32,   36,
       37,   24,   37,   35,   24,   24,   24,   24,   36,   24,
       35,   37,   40,   43,   43,   30,   35,   24,   38,   40,
       48,   38,  360,   43,   76,  359,   43,   24,   60,   60,
       60,   72,   72,   72,   24,   25,   84,   25,   25,   25,
       75,   75,   75,   77,   77,   77,   72,  358,  123,   25,
      123,   76,   25,   25,   25,   75,   78,   25,   78,   78,
       78,   77,   79,   84,   79,   25,  114,  157,   79,   79,
       78,  116,  119,  114,   78,   25,   52,   81,   78,   81,

       52,  116,  116,   81,   81,  357,   78,  119,   77,   52,
       52,  122,   85,   85,   85,   87,   78,   87,  345,  122,
      157,   87,   87,  131,  131,  132,  132,  146,  146,   52,
       85,  147,  147,   52,   52,  160,  160,  160,   52,  163,
      167,  167,  168,  168,  168,   52,  170,  170,   52,  174,
       52,  339,   52,  337,   52,   56,  336,   85,  334,   56,
      165,  333,  165,  165,  165,  331,  163,  330,   56,   56,
      171,  171,  171,  329,  165,  326,  174,  325,  165,  175,
      175,  324,  165,  176,  176,  188,  188,  317,   56,  316,
      165,  312,   56,   56,  215,  215,  311,   56,  217,  217,

      165,  177,  177,  177,   56,  310,  309,   56,  300,   56,
      299,   56,  297,   56,  166,  296,  166,  166,  166,  222,
      222,  222,  172,  172,  172,  219,  219,  219,  166,  295,
      177,  294,  166,  293,  166,  292,  166,  172,  172,  172,
      290,  219,  172,  289,  166,  219,  227,  227,  221,  288,
      221,  221,  221,  287,  166,  223,  223,  223,  285,  284,
      172,  166,  221,  219,  227,  283,  221,  225,  225,  225,
      221,  226,  226,  226,  228,  228,  228,  282,  221,  231,
      231,  231,  232,  232,  232,  270,  270,  279,  221,  278,
      276,  227,  271,  271,  271,  273,  273,  273,  274,  274,

      274,  267,  266,  270,  275,  275,  275,  264,  231,  263,
      262,  232,  303,  303,  303,  304,  304,  304,  305,  305,
      305,  306,  306,  306,  307,  307,  307,  327,  327,  327,
      270,  328,  328,  328,  348,  348,  348,  348,  348,  348,
      349,  349,  349,  349,  349,  349,  350,  350,  350,  350,
      350,  350,  351,  351,  352,  261,  352,  260,  352,  352,
      353,  353,  353,  353,  353,  353,  354,  259,  258,  354,
      354,  354,  355,  355,  355,  355,  355,  355,  356,  356,
      356,  356,  356,  356,  257,  256,  255,  254,  253,  251,
      249,  248,  245,  244,  243,  242,  239,  237,  236,  235,

      229,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  197,  196,  194,
      193,  192,  191,  190,  189,  187,  186,  185,  184,  183,
      182,  181,  178,  169,  159,  124,  121,  120,  117,  115,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   94,   90,   88,   80,
       71,   47,   46,   45,   44,   42,   41,   39,   34,   33,
       31,   27,   23,   19,   15,   12,    9,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "eslex.l"
#line 3 "eslex.l"
//EUGENE SOKOLOV
//COMPILERS ECE466
//LEXICAL ANALYSIS: lex.l

#include "tokens-manual.h"
#include "yylval.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

YYSTYPE yylval;

unsigned int lineno = 1;
unsigned int string_length = 0;
char filename[MAX_STRING_LENGTH];
char *tmp_ptr;
char tmp_string[MAX_STRING_LENGTH];

#line 739 "lex.yy.c"

#define INITIAL 0
#define IN_CHAR 1
#define IN_STRING 2
#define IN_FILE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 30 "eslex.l"


#line 932 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 348 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 578 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 32 "eslex.l"
{keyword(lineno,yytext);return AUTO;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "eslex.l"
{keyword(lineno,yytext);return BREAK;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 34 "eslex.l"
{keyword(lineno,yytext);return CASE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "eslex.l"
{keyword(lineno,yytext);return CHAR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 36 "eslex.l"
{keyword(lineno,yytext);return CONST;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 37 "eslex.l"
{keyword(lineno,yytext);return CONTINUE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 38 "eslex.l"
{keyword(lineno,yytext);return DEFAULT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "eslex.l"
{keyword(lineno,yytext);return DO;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "eslex.l"
{keyword(lineno,yytext);return DOUBLE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "eslex.l"
{keyword(lineno,yytext);return ELSE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "eslex.l"
{keyword(lineno,yytext);return ENUM;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "eslex.l"
{keyword(lineno,yytext);return EXTERN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "eslex.l"
{keyword(lineno,yytext);return FLOAT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "eslex.l"
{keyword(lineno,yytext);return FOR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "eslex.l"
{keyword(lineno,yytext);return GOTO;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "eslex.l"
{keyword(lineno,yytext);return IF;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "eslex.l"
{keyword(lineno,yytext);return INLINE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "eslex.l"
{keyword(lineno,yytext);return INT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "eslex.l"
{keyword(lineno,yytext);return LONG;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "eslex.l"
{keyword(lineno,yytext);return REGISTER;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "eslex.l"
{keyword(lineno,yytext);return RESTRICT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "eslex.l"
{keyword(lineno,yytext);return RETURN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "eslex.l"
{keyword(lineno,yytext);return SHORT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "eslex.l"
{keyword(lineno,yytext);return SIGNED;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "eslex.l"
{keyword(lineno,yytext);return SIZEOF;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "eslex.l"
{keyword(lineno,yytext);return STATIC;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "eslex.l"
{keyword(lineno,yytext);return STRUCT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "eslex.l"
{keyword(lineno,yytext);return SWITCH;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "eslex.l"
{keyword(lineno,yytext);return TYPEDEF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "eslex.l"
{keyword(lineno,yytext);return UNION;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "eslex.l"
{keyword(lineno,yytext);return UNSIGNED;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "eslex.l"
{keyword(lineno,yytext);return VOID;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "eslex.l"
{keyword(lineno,yytext);return VOLATILE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "eslex.l"
{keyword(lineno,yytext);return WHILE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 66 "eslex.l"
{keyword(lineno,yytext);return _BOOL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 67 "eslex.l"
{keyword(lineno,yytext);return _COMPLEX;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 68 "eslex.l"
{keyword(lineno,yytext);return _IMAGINARY;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "eslex.l"
{printf("%s\t %d\t PLUSPLUS\n",filename,lineno);return PLUSPLUS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 71 "eslex.l"
{printf("%s\t %d\t MINUSMINUS\n",filename,lineno);return MINUSMINUS;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 72 "eslex.l"
{printf("%s\t %d\t ELLIPSIS\n",filename, lineno);return ELLIPSIS;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 73 "eslex.l"
{printf("%s\t %d\t NOTEQ\n",filename, lineno);return NOTEQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 74 "eslex.l"
{printf("%s\t %d\t PLUSEQ\n",filename, lineno);return PLUSEQ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 75 "eslex.l"
{printf("%s\t %d\t MINUSEQ\n",filename, lineno);return MINUSEQ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 76 "eslex.l"
{printf("%s\t %d\t DIVEQ\n",filename, lineno);return DIVEQ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 77 "eslex.l"
{printf("%s\t %d\t TIMESEQ\n",filename, lineno);return TIMESEQ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 78 "eslex.l"
{printf("%s\t %d\t XOREQ\n",filename, lineno);return XOREQ;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 79 "eslex.l"
{printf("%s\t %d\t OREQ\n",filename, lineno);return OREQ;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 80 "eslex.l"
{printf("%s\t %d\t ANDEQ\n",filename, lineno);return ANDEQ;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 81 "eslex.l"
{printf("%s\t %d\t MODEQ\n",filename, lineno);return MODEQ;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 82 "eslex.l"
{printf("%s\t %d\t INDSEL\n",filename, lineno);return INDSEL;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 83 "eslex.l"
{printf("%s\t %d\t LOGAND\n",filename, lineno);return LOGAND;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 84 "eslex.l"
{printf("%s\t %d\t LOGOR\n",filename, lineno);return LOGOR;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 85 "eslex.l"
{printf("%s\t %d\t LTEQ\n",filename, lineno);return LTEQ;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 86 "eslex.l"
{printf("%s\t %d\t GTEQ\n",filename, lineno);return GTEQ;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 87 "eslex.l"
{printf("%s\t %d\t SHLEQ\n",filename, lineno);return SHLEQ;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 88 "eslex.l"
{printf("%s\t %d\t SHL\n",filename, lineno);return SHL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 89 "eslex.l"
{printf("%s\t %d\t SHREQ\n",filename, lineno);return SHREQ;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 90 "eslex.l"
{printf("%s\t %d\t SHR\n",filename, lineno);return SHR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 91 "eslex.l"
{printf("%s\t %d\t EQEQ\n",filename, lineno);return EQEQ;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 92 "eslex.l"
{printf("%s\t %d\t %s\n",filename, lineno, yytext);}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 93 "eslex.l"
{lineno++;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 95 "eslex.l"
{
	yylval.word.yystring=strdup(yytext);
	yylval.word.yystring_size=strlen(yytext);
	return IDENT;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "eslex.l"
{tmp_ptr=tmp_string;string_length=0;BEGIN(IN_CHAR);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "eslex.l"
{tmp_ptr=tmp_string;string_length=0;BEGIN(IN_STRING);}
	YY_BREAK

case 65:
YY_RULE_SETUP
#line 105 "eslex.l"
{
	BEGIN(INITIAL); 
	*tmp_ptr = '\0'; 
	yylval.word.yychar = tmp_string[0]; 
	return CHARLIT;
	}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 111 "eslex.l"
{fprintf(stderr, "%s:%d:Error:Unterminated string constant\n", filename, lineno);exit(1);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 112 "eslex.l"
{*tmp_ptr='\0';tmp_ptr++;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 113 "eslex.l"
{*tmp_ptr='\a';tmp_ptr++;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 114 "eslex.l"
{*tmp_ptr='\b';tmp_ptr++;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "eslex.l"
{*tmp_ptr='\f';tmp_ptr++;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "eslex.l"
{*tmp_ptr='\n';tmp_ptr++;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "eslex.l"
{*tmp_ptr='\r';tmp_ptr++;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "eslex.l"
{*tmp_ptr='\t';tmp_ptr++;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "eslex.l"
{*tmp_ptr='\v';tmp_ptr++;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "eslex.l"
{*tmp_ptr='\"';tmp_ptr++;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 121 "eslex.l"
{*tmp_ptr='\\';tmp_ptr++;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 122 "eslex.l"
{*tmp_ptr='\'';tmp_ptr++;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 123 "eslex.l"
{
        int tmp;
        sscanf(yytext+1, "%o", &tmp);
        if (tmp > 0xff){
            fprintf(stderr, "%s:%d:Warning:Octal escape sequence %s out of range", filename, lineno, yytext);
            tmp = '\377';
        }
        *tmp_ptr=tmp;
	tmp_ptr++;
    }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 133 "eslex.l"
{
        int tmp;
        sscanf(yytext+2, "%x", &tmp);
        if (tmp > 0xff){
            fprintf(stderr, "%s:%d:Warning:Hex escape sequence %s out of range", filename, lineno, yytext);
            tmp = '\377';
        }
        *tmp_ptr=tmp;
	tmp_ptr++;
    }
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 143 "eslex.l"
{*tmp_ptr=yytext[1];tmp_ptr++;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 144 "eslex.l"
{
	char *yptr = yytext;
        while (*yptr){
		*tmp_ptr = *yptr++;
		tmp_ptr++;
	}
    }
	YY_BREAK


case 82:
YY_RULE_SETUP
#line 154 "eslex.l"
{
	BEGIN(INITIAL); 
	*tmp_ptr = '\0'; 
	yylval.word.yystring = tmp_string; 
	return STRING;
	}
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 160 "eslex.l"
{fprintf(stderr, "%s:%d:Error:Unterminated string constant\n", filename, lineno);exit(1);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 161 "eslex.l"
{*tmp_ptr='\0';tmp_ptr++;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 162 "eslex.l"
{*tmp_ptr='\a';tmp_ptr++;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 163 "eslex.l"
{*tmp_ptr='\b';tmp_ptr++;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 164 "eslex.l"
{*tmp_ptr='\f';tmp_ptr++;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 165 "eslex.l"
{*tmp_ptr='\n';tmp_ptr++;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 166 "eslex.l"
{*tmp_ptr='\r';tmp_ptr++;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 167 "eslex.l"
{*tmp_ptr='\t';tmp_ptr++;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 168 "eslex.l"
{*tmp_ptr='\v';tmp_ptr++;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 169 "eslex.l"
{*tmp_ptr='\"';tmp_ptr++;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 170 "eslex.l"
{*tmp_ptr='\\';tmp_ptr++;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 171 "eslex.l"
{*tmp_ptr='\'';tmp_ptr++;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 172 "eslex.l"
{
        int tmp;
        sscanf(yytext+1, "%o", &tmp);
        if (tmp > 0xff){
            fprintf(stderr, "%s:%d:Warning:Octal escape sequence %s out of range\n", filename, lineno, yytext);
            tmp = '\377';
        }
        *tmp_ptr=tmp;
	tmp_ptr++;
    }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 182 "eslex.l"
{
        int tmp;
        sscanf(yytext+2, "%x", &tmp);
        if (tmp > 0xff){
            fprintf(stderr, "%s:%d:Warning:Hex escape sequence %s out of range\n", filename, lineno, yytext);
            tmp = '\377';
        }
        *tmp_ptr=tmp;
	tmp_ptr++;
    }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 192 "eslex.l"
{*tmp_ptr=yytext[1];tmp_ptr++;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 193 "eslex.l"
{
        char *yptr = yytext;
        while (*yptr){
		*tmp_ptr=*yptr++;
		*tmp_ptr++;
	}
    }
	YY_BREAK

case 99:
YY_RULE_SETUP
#line 202 "eslex.l"
{
	yylval.number.yyint=atoi(yytext);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 208 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	yylval.number.yyint=atoi(yytext);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 216 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	yylval.number.yyint=atoi(yytext);
	yylval.number.num_type=TYPE_LONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 223 "eslex.l"
{	
	yytext[yyleng-2] = '\0';
	yylval.number.yyint=atoi(yytext);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 230 "eslex.l"
{
	yytext[yyleng-3] = '\0';
	yylval.number.yyint=atoi(yytext);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 238 "eslex.l"
{
	sscanf(yytext, "%llo", &yylval.number.yyint);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 244 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%llo", &yylval.number.yyint);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 251 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%llo", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 258 "eslex.l"
{
	yytext[yyleng-2] = '\0';
	sscanf(yytext, "%llo", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 265 "eslex.l"
{
	yytext[yyleng-3] = '\0';
	sscanf(yytext, "%llo", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 273 "eslex.l"
{
	sscanf(yytext, "%llx", &yylval.number.yyint);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 279 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%llx", &yylval.number.yyint);
	yylval.number.num_type=TYPE_INT;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 286 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%llx", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 293 "eslex.l"
{
	yytext[yyleng-2] = '\0';
	sscanf(yytext, "%llx", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 300 "eslex.l"
{
	yytext[yyleng-3] = '\0';
	sscanf(yytext, "%llx", &yylval.number.yyint);
	yylval.number.num_type=TYPE_LONGLONG;
	yylval.number.num_sign=TYPE_UNSIGNED;
	return NUMBER;
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 308 "eslex.l"
{
	sscanf(yytext, "%Lf", &yylval.number.yydouble);
	yylval.number.num_type=TYPE_DOUBLE;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 314 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%Lf", &yylval.number.yydouble);
	yylval.number.num_type=TYPE_LONGDOUBLE;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 322 "eslex.l"
{
	sscanf(yytext, "%Lf", &yylval.number.yydouble);
	yylval.number.num_type=TYPE_DOUBLE;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 328 "eslex.l"
{
	sscanf(yytext, "%Lf", &yylval.number.yydouble);
	yylval.number.num_type=TYPE_DOUBLE;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 335 "eslex.l"
{
	yytext[yyleng-1] = '\0';
	sscanf(yytext, "%Lf", &yylval.number.yydouble);
	yylval.number.num_type=TYPE_FLOAT;
	yylval.number.num_sign=TYPE_SIGNED;
	return NUMBER;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 343 "eslex.l"
{BEGIN(IN_FILE);}
	YY_BREAK

case 120:
/* rule 120 can match eol */
YY_RULE_SETUP
#line 345 "eslex.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 346 "eslex.l"
{}
	YY_BREAK
case 122:
/* rule 122 can match eol */
YY_RULE_SETUP
#line 347 "eslex.l"
{strncpy(filename, yytext+1, strlen(yytext)-2);filename[strlen(yytext)-2]='\0';}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 348 "eslex.l"
{}
	YY_BREAK

case 124:
YY_RULE_SETUP
#line 351 "eslex.l"
{fprintf(stderr,"Error: undefined token %s\n", yytext);exit(1);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 353 "eslex.l"
ECHO;
	YY_BREAK
#line 1829 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_CHAR):
case YY_STATE_EOF(IN_STRING):
case YY_STATE_EOF(IN_FILE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 348 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 348 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 347);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 353 "eslex.l"




printchars(char *str, char *end){
	while (str != end){
		switch (*str){
		    case '\0':
		        printf("\\0");
		    case '\a':
		        printf("\\a");
		        break;
		    case '\b':
		        printf("\\b");
		        break;
		    case '\f':
		        printf("\\f");
		        break;
		    case '\n':
		        printf("\\n");
		        break;
		    case '\r':
		        printf("\\r");
		        break;
		    case '\t':
		        printf("\\t");
		        break;
		    case '\v':
		        printf("\\v");
		        break;
		    case '\"':
		        printf("\\\"");
		        break;
		        break;
		    case '\\':
		        printf("\\\\");
		        break;
		    case '\'':
		        printf("\\\'");
		        break;
		    default:
		        if (*str > 126 || *str < 32){
		            printf("\\%03o", (unsigned char)*str);
		        } else {
		            printf("%c", *str);
		        }
		        break;
		}
		str++;
    	}
	printf("\n");
}

keyword(int lineno, char* yytext){

	char *p = yytext;
	while(*p != '\0'){
		*p=toupper(*p);
 		p++;
	}
 	printf("%s\t %d\t %s\n",filename, lineno, yytext);
}

/*
int main(){
   int token;
   while(token=yylex()){
	switch(token){
		case IDENT:
			printf("%s\t %d\t IDENT\t %s\n",filename, lineno, yylval.word.yystring);
			break;
		case STRING:
			printf("%s\t %d\t STRING\t ",filename, lineno);
			printchars(tmp_string, tmp_ptr);	
			break;
		case CHARLIT:
			printf("%s\t %d\t CHARLIT\t ",filename, lineno);
			printchars(tmp_string, tmp_string+1);	
			break;
		case NUMBER:
			printf("%s\t %d\t NUMBER\t",filename,lineno);
			if(yylval.number.num_type==TYPE_INT || yylval.number.num_type==TYPE_LONG)
				printf("INTEGER\t %lld\t", yylval.number.yyint);
			else
				printf("REAL\t %Lg\t", yylval.number.yydouble);
			if(yylval.number.num_sign==TYPE_UNSIGNED)
				printf("UNSIGNED,");
			switch(yylval.number.num_type){
				case TYPE_INT:	printf("INT\n");break;
				case TYPE_LONG:	printf("LONG\n");break;
				case TYPE_LONGLONG: printf("LONGLONG\n");break;
				case TYPE_LONGDOUBLE: printf("LONGDOUBLE\n");break;
				case TYPE_DOUBLE: printf("DOUBLE\n");break;
				case TYPE_FLOAT: printf("FLOAT\n");break;
				default: printf("error\n");break;
			}
			break;
		default:
			break;

	}

   }
}
*/

